### ISSUE TITLE
Handle unsupported input categories

### ISSUE THREAD

**Issue by maximusunc** [TranslatorSRI/TestHarness#26]
Traceback (most recent call last):
  File "/usr/local/bin/test-harness", line 33, in <module>
    sys.exit(load_entry_point('sri-test-harness', 'console_scripts', 'test-harness')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/test_harness/main.py", line 129, in cli
    asyncio.run(main(vars(args)))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/test_harness/main.py", line 51, in main
    report = await run_tests(reporter, slacker, tests, logger, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/test_harness/run.py", line 57, in run_tests
    query_responses, normalized_curies = await query_runner.run_queries(test)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/test_harness/runner/query_runner.py", line 99, in run_queries
    query = generate_query(test_asset)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/test_harness/runner/generate_query.py", line 91, in generate_query
    raise Exception("Unsupported input category.")
Exception: Unsupported input category.

**Comment by maximusunc** [comment]
Handled by #29
